version: '3'
services:
  database:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: fe_app_development
  web:
    image: mahshaban95/frontend-assignment_web:1.0
    # command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && bin/rails db:migrate RAILS_ENV=development"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - "database"
