name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag myapp:$(date +%s)

    # - uses: isbang/compose-action@v1.3.2
    #   with:
    #     compose-file: "./docker-compose.yml"

    - name: Create tag
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: actions/github-script@v6
      with:
        script: |
          echo "NOW=efs/tags/v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: $Tag ,
            sha: context.sha
          })
        env:
          Tag: $(date +'%Y%m%d.%H%M%S')